// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niaiuneltiqshbwztgxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pYWl1bmVsdGlxc2hid3p0Z3hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTY5MTcsImV4cCI6MjA3MTk3MjkxN30.Kx4R2z9X_UyFzTQ14rF1Nt6UqwkNyFrMDW4f9J9yxrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});